project:
  type: book
  output-dir: docs

book:
  title: "EPI519 Evolutionary Epidemiology"
  author: "Christian Testa"
  date: "10/24/2023"
  chapters:
    - index.qmd
    - week1/week1.qmd
    - week2/week2.qmd
    - week3/week3.qmd
    - week4/week4.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



